### PR TITLE
use lean nightly builds instead of github build-artifacts

### PR DESCRIPTION
**Pull request by lovettchris**
This PR should be merged at the same time as this matching PR over in Lean4:

https://github.com/leanprover/theorem_proving_in_lean4/pull/42

### CODE REVIEW

**Comment by Kha** [comment]
@lovettchris Could you rebase?

**Comment by lovettchris** [comment]
> @lovettchris Could you rebase?

Done.

**Comment by Kha** [comment]
Now the only remaining issue with this setup that I can think of is that only the last person that touch `ci.yml`, which is probably me now, will be notified of a broken nightly run. @lovettchris Do you have any ideas on how to improve this? What would be cool is to have the CI automatically file an issue when the nightly run breaks, though it probably should do so only if there is no existing such issue. /cc @leodemoura

**Comment by lovettchris** [comment]
I think Leo has been tracking the status of these builds and making fixes as needed.  It is interesting that the tests [passed just 19 hours ago ](https://github.com/leanprover/theorem_proving_in_lean4/actions/runs/2777886836) using the build artifact, but failed just now when we switched to the nightly build...?

**Comment by Kha** [comment]
Hmm, why did you stop overriding `lean-toolchain`? That won't work.

**Comment by lovettchris** [comment]
Oops, you are right, I think what will work is to change the lean-toolchain to contain this instead "leanprover/lean4:nightly".

**Comment by lovettchris** [comment]
Try this: https://github.com/leanprover/theorem_proving_in_lean4/pull/45

**Pull request merged**
